server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://39.108.50.125:3306/fupin?serverTimezone=UTC
    username: root
    password: 85000464
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/application-fupin.log